term=xterm-256color
font=FantasqueSansM Nerd Font:size=7.85
pad=12x12 center
dpi-aware=yes
gamma-correct-blending=yes
bold-text-in-bright=yes
workers=3

[mouse]
hide-when-typing=yes

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[key-bindings]
show-urls-launch=Control+Shift+o
show-urls-copy=Control+Shift+y

[colors-dark]
alpha=0.95
blur=yes
# cursor=e0def4 232136
foreground=e0def4
background=232136

regular0=393552
regular1=eb6f92
regular2=3e8fb0
regular3=f6c177
regular4=c4a7e7
regular5=ea9a97
regular6=9ccfd8
regular7=e0def4

bright0=6e6a86
bright1=eb6f92
bright2=3e8fb0
bright3=f6c177
bright4=c4a7e7
bright5=ea9a97
bright6=9ccfd8
bright7=e0def4

16=908caa
17=908caa

selection-foreground=e0def4
selection-background=44415a

search-box-no-match=232136 eb6f92
search-box-match=e0def4 393552

jump-labels=232136 c4a7e7
urls=c4a7e7
