# set term to xterm256-color
term xterm-256color

# set display server use x11
# linux_display_server x11

# window size and properties
remember_window_size no
initial_window_width 100c
initial_window_height 40c

# performance
input_delay 0
repaint_delay 5
sync_to_monitor no
wayland_enable_ime no

# cursor trail
cursor_trail 14
cursor_trail_start_threshold 0
cursor_trail_decay 0.03 0.08
cursor_shape beam
cursor_blink_interval 0.8


# fonts
# font_family ComicShannsMono Nerd Font Mono
# font_family MartianMono Nerd Font Mono
font_family FantasqueSansM Nerd Font Mono
font_size 16.5
# disable_ligatures always

# themes
dynamic_background_opacity yes
# background_opacity 0.85
# include themes/CatppuccinMocha.conf
include themes/gruvbox_dark.conf

# padding
window_padding_width 4

# map
# map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+t none
